config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  post 'messages', to: 'messages#create'
 
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  root to: "posts#index"

  get "/home", to: "home#index"
  
  resources :posts
  get "/show_notification", to: "posts#show_notification"
  
  resources :comments

  resources :likes, only: [:create, :destroy]
  
  resources :user_profile

  get '/another_user/:id', to: "user_profile#another_user"

  resources :friendshipes

  get '/add_new_friend', to: "friendshipes#add_new_friend"

  get '/friend', to: "friendshipes#friend"
 
  get '/see_friend_request', to: "friendshipes#see_friend_request"

  get '/chat', to: "pages#chat"


  resources :rooms do
    resources :msgs
  end

  get 'user/:id', to: 'users#show', as: 'user'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :body, presence: true  
end

app/models/friendship.rb
class Friendship < ApplicationRecord	
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit {
    MessageBroadcastJob.perform_later(self)
  }
end

app/models/msg.rb
class Msg < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private

      is_participant = Participant.where(user_id: user.id, room_id: room.id).first
      throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_one_attached :image 
	validates :title, presence: true, length: { maximum: 20 }
  validates :description, presence: true 
  validates :image, presence: true
  scope :recent_first, -> {order(created_at: :desc)}
  
end

app/models/room.rb
class Room < ApplicationRecord
	validates_uniqueness_of :name
	scope :public_rooms, -> {where(is_private: false)}
	after_create_commit { broadcast_if_public }
	has_many :msgs
	has_many :participants, dependent: :destroy
	
 def broadcast_if_public
   broadcast_append_to "rooms" unless self.is_private
 end
 def self.create_private_room(users, room_name)
   single_room = Room.create(name: room_name, is_private: true)
   users.each do |user|
     Participant.create(user_id: user.id, room_id: single_room.id)
   end
   single_room
 end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    scope :all_except, ->(user) {where.not(id:user)} 

    validates :email,
      presence: true,
      length: { maximum: 50 },
      format: { with: URI::MailTo::EMAIL_REGEXP },
      uniqueness: true
    
    validates :name, presence: true,  
              :length => { minimum: 4 },
              :uniqueness => { case_sensitive: false }
              
    validates :address, presence: true  
  
    validates :mobile_no,:presence => true,
              :numericality => true,
              :length => { :minimum => 10, :maximum => 12 }

    has_many :posts  
    has_many :comments
    has_many :likes
    has_one_attached :profilepic 

    after_create_commit { broadcast_append_to "users" } 
    has_many :msgs
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gits/edit.html.erb
<html>kushwah</html>

app/views/gits/index.html.erb
<html>raju</html>

app/views/shareds/_navber.html.erb
<nav class="navbar navbar-dark bg-dark justify-content-between">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="">Social media app</a>
     
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li class="nav-item">
            <a class="navbar-brand" href="/">Home</a>
           </li>

            <li class="nav-item">
              <%= link_to 'Profile', user_profile_path(current_user), class:'navbar-brand'%>
            </li>

            <li class="nav-item">
              <%= link_to 'Group Chats', chat_path, class:'navbar-brand'%>
            </li> 

            <li class="nav-item">
              <%= link_to 'Start Chatting', rooms_path, class:'navbar-brand'%>
            </li> 

            <li class="nav-item">
              <%= link_to "Notification", href="/show_notification", class:'navbar-brand'%>
            </li> 


            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:'navbar-brand' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Register', new_user_registration_path, class:'navbar-brand'%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class:'navbar-brand'%>
            </li>
          <% end %>

        </ul>
      </div>   
    </div>
  </nav>
</nav>