config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  post 'messages', to: 'messages#create'
 
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  root to: "posts#index"

  get "/home", to: "home#index"
  
  resources :posts
  get "/show_notification", to: "posts#show_notification"
  
  resources :comments

  resources :likes, only: [:create, :destroy]
  
  resources :user_profile

  get '/another_user/:id', to: "user_profile#another_user"

  resources :friendshipes

  get '/add_new_friend', to: "friendshipes#add_new_friend"

  get '/friend', to: "friendshipes#friend"
 
  get '/see_friend_request', to: "friendshipes#see_friend_request"

  get '/chat', to: "pages#chat"


  resources :rooms do
    resources :msgs
  end

  get 'user/:id', to: 'users#show', as: 'user'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :body, presence: true  
end

app/models/friendship.rb
class Friendship < ApplicationRecord	
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit {
    MessageBroadcastJob.perform_later(self)
  }
end

app/models/msg.rb
class Msg < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private

      is_participant = Participant.where(user_id: user.id, room_id: room.id).first
      throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_one_attached :image 
	validates :title, presence: true, length: { maximum: 20 }
  validates :description, presence: true 
  validates :image, presence: true
  scope :recent_first, -> {order(created_at: :desc)}
  
end

app/models/room.rb
class Room < ApplicationRecord
	validates_uniqueness_of :name
	scope :public_rooms, -> {where(is_private: false)}
	after_create_commit { broadcast_if_public }
	has_many :msgs
	has_many :participants, dependent: :destroy
	
 def broadcast_if_public
   broadcast_append_to "rooms" unless self.is_private
 end
 def self.create_private_room(users, room_name)
   single_room = Room.create(name: room_name, is_private: true)
   users.each do |user|
     Participant.create(user_id: user.id, room_id: single_room.id)
   end
   single_room
 end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    scope :all_except, ->(user) {where.not(id:user)} 

    validates :email,
      presence: true,
      length: { maximum: 50 },
      format: { with: URI::MailTo::EMAIL_REGEXP },
      uniqueness: true
    
    validates :name, presence: true,  
              :length => { minimum: 4 },
              :uniqueness => { case_sensitive: false }
              
    validates :address, presence: true  
  
    validates :mobile_no,:presence => true,
              :numericality => true,
              :length => { :minimum => 10, :maximum => 12 }

    has_many :posts  
    has_many :comments
    has_many :likes
    has_one_attached :profilepic 

    after_create_commit { broadcast_append_to "users" } 
    has_many :msgs
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    ActionCable.server.broadcast('notification_channel', 'You have visited the welcome page.')
  end  
end

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController
 def create
  @message = current_user.msgs.create(body: msg_params[:body], room_id: params[:room_id])
 end

 private
 def msg_params
  params.require(:msg).permit(:body)
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index 
    friends_ids = Friendship.where(sender_id: current_user.id, confirmation: true)&.map(&:receiver_id)
    accepted_friends_ids = Friendship.where(receiver_id: current_user.id, confirmation: true)&.map(&:sender_id)
    @total_friends_ids = (friends_ids + accepted_friends_ids).uniq
    @total_friends_ids << current_user.id
    @posts = Post.where(user_id: @total_friends_ids).order("updated_at desc")
  end
     
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      PostMailer.with(user: current_user, post: @post).post_created.deliver_later
      redirect_to @post
    else
      render 'new', status: :unprocessable_entity
    end   
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    # if @post.user_id != current_user.id
    #   redirect_to posts_path
    # end    
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
 
  def destroy  
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def show_notification
    friends_ids = Friendship.where(sender_id: current_user.id, confirmation: true)&.map(&:receiver_id)
    accepted_friends_ids = Friendship.where(receiver_id: current_user.id, confirmation: true)&.map(&:sender_id)
    @total_friends_ids = (friends_ids + accepted_friends_ids).uniq
    @posts = Post.where(user_id: @total_friends_ids, created_at: Time.current.all_day).order("updated_at desc")

  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :image )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<h2 style="color:Tomato;"> New Post </h2>
<%= form_for @post do |form| %>
  <% if @post.errors.any? %>
      <h2>Errors:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>   
  <% end %>
 
  <div class="field from-group">
    <u><%= form.label :title %></u>
    <%= form.text_field :title, class:"form-control" %>
  </div><br>

  <div class="field from-group">
    <u><%= form.label :image %></u>
    <%= form.file_field :image, class:"form-control" %>
    <td><%image_tag @post.image if @post.image.attached? %></td>
  </div><br>

   <div class="field from-group">
    <u> <%= form.label :description %></u>
    <%= form.text_area :description,size: "60x10", class:"form-control" %>
  </div>
  <%= form.submit 'submit', class:"btn btn-primary" %>
  <%= link_to 'Back', posts_path, class:"btn btn-info" %>
<% end %>

app/views/posts/edit.html.erb
<h1 style="color:Tomato;"> Post Edit From </h1>
<%= form_with model: @post do |form| %>
  <% if @post.errors %>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field from-group">
    <u><%= form.label :title %></u><br><br>
    <%= form.text_field :title, class:"form-control" %><br><br>
  </div>

  <div class="field from-group">
    <u><%= form.label :image %></u><br><br>
    <%= form.file_field :image, class:"form-control" %><br><br>
    <td><%image_tag @post.image if @post.image.attached? %></td>
  </div>

   <div class="field from-group">
    <u> <%= form.label :description %></u><br><br>
    <%= form.text_area :description,size: "60x10", class:"form-control" %><br><br>
  </div>

  <%= form.submit %><br><br>
<% end %>


  

app/views/posts/index.html.erb
<div>
  <%= link_to '+post', new_post_path, class:"btn btn-primary" %>
  <%= link_to 'Send Notification', home_path, remote: true, class:"btn btn-primary" %>  
  <div class="row">
	  <% @posts.each do |post| %>
	
		    <div class="card col-md-3" style="height: 400px; background-color: #b3d9ff;">
		    	<!-- <h5 class="card-title"><%= link_to post.user.name, user_profile_path(post.user) %></h5> -->
		    	<h5 class="card-title"><%= post.user.name %></h5>

		    	<% if post.image.attached? %>
			     <%= image_tag post&.image, class:"card-img-top", style: "height: 174px" %>
			    <%end%>
				  <div class="card-body">
				    <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
				    <p class="card-text"><%= post.description %></p>
				    <div style="margin-bottom: 10px;">
				    	<%= form_with model: Comment.new do |form| %>
				        <%= hidden_field_tag :post_id, post.id %>
				        <%= form.text_field :body, placeholder: "Comment", style: "width: 100px; display: inline" %>
				        <%= form.submit 'submit' %>
				        <%= link_to 'See', post_path(post), class:"btn btn-primary" %>
	            <% end %>
				    </div>
	          <div>
	          	<div style="float: left;">
	          		<%= post.likes.count %> 
	          		<% like = current_user.likes.find_by(post: post) %> 
						    <% if like.nil? %>
						        <%=  link_to likes_path({ like: { post_id: post.id } }), method: :post do %>
	                    <%= image_tag "like-inactive.png", style: "height: 40px;" %>
						        <% end %>
						    <% else %>
						        <%=  link_to  like_path(like), method: :delete do %>
						        <%= image_tag "like-active.png", style: "height: 40px;" %>
						        <% end %>
						    <% end %>
	          	</div>
	          	
					    <div style="float: right;">
					    	<% if post.user == current_user %>
						    	<%= link_to 'Edit', edit_post_path(post), class:"btn btn-warning" %>
				      		<%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

				      	<% end %>
			      	</div> 
			      </div>
				  </div>
				</div>
		<% end %>
	</div>  

</div> 

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<body>
  <div class= "container">
    <div class="Links">
      <div>
       <%= link_to 'Index post', posts_path, class:"btn btn-primary" %>
       <%= link_to 'New post', new_post_path, class:"btn btn-primary" %>
       <%= link_to 'Back', posts_path, class:"btn btn-info" %>
      </div>
    </div>

    <div class="container">
      <div class="post_title">
         <h1><%= @post.title.titleize()%></h1>
      </div>

      <div class="post_title">
        <h1><%= @post.likes.count %> Likes</h1> 
      </div>
    </div>
    
    <div style="width: 100%;">
      <div class="leftpane">
        <div class="card" style="width: 34rem;">
          <h5 class="card-title"><%= @post.user.name %></h5>
          <% if @post.image.attached? %>
           <%= image_tag @post.image %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text"><%= @post.description%></p>
          </div>
          <div>
            <%= form_with model: Comment.new do |form| %>      
              <ul>
                <li>
                  <span>
                  <%= hidden_field_tag :post_id, @post.id %>
                  <%= form.text_field :body , placeholder: "Enter your Comment"%>
                </span>
                <span>
                  <%= form.submit 'submit', class: "btn btn-success" %><br><br>
                </span>
                </li>
              </ul>
            <% end %>
          </div> 
        </div>
      </div> 
    </div> 
  </div>

  <div >
      <div class="rightpane">
        <h2>Comments</h2>
        <table >
          <thead>
            <tr>
              <th>Name</th>
              <th>Comment</th>
            </tr>
          </thead>
          <tbody>
            <% @post.comments.each do |c|%>
              <tr>
                <td><%= c.user.name %></td>
                <td><%= c.body%></td>
                <td>

                 <% if c.user == current_user %>
                    <%= link_to 'Edit', edit_comment_path(c),class:"btn btn-warning" %> 
                    <%= link_to 'Destroy', comment_path(c),
                              method: :delete,
                            data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</body>  

app/views/posts/show_notification.html.erb
 <div>
  <%= link_to 'Back', posts_path, class:"btn btn-primary" %>
  <%= link_to 'Send Notification', home_path, remote: true, class:"btn btn-primary" %>  
  <div class="row">
    <% @posts.each do |post| %>
  
        <div class="card col-md-3" style="height: 400px; background-color: #b3d9ff;">
          <!-- <h5 class="card-title"><%= link_to post.user.name, user_profile_path(post.user) %></h5> -->
          <h5 class="card-title"><%= post.user.name %></h5>

          <% if post.image.attached? %>
           <%= image_tag post&.image, class:"card-img-top", style: "height: 174px" %>
          <%end%>
          <div class="card-body">
            <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
            <p class="card-text"><%= post.description %></p>
            <div style="margin-bottom: 10px;">
              <%= form_with model: Comment.new do |form| %>
                <%= hidden_field_tag :post_id, post.id %>
                <%= form.text_field :body, placeholder: "Comment", style: "width: 100px; display: inline" %>
                <%= form.submit 'submit' %>
                <%= link_to 'See', post_path(post), class:"btn btn-primary" %>
              <% end %>
            </div>
            <div>
              <div style="float: left;">
                <%= post.likes.count %> 
                <% like = current_user.likes.find_by(post: post) %> 
                <% if like.nil? %>
                    <%=  link_to likes_path({ like: { post_id: post.id } }), method: :post do %>
                      <%= image_tag "like-inactive.png", style: "height: 40px;" %>
                    <% end %>
                <% else %>
                    <%=  link_to  like_path(like), method: :delete do %>
                    <%= image_tag "like-active.png", style: "height: 40px;" %>
                    <% end %>
                <% end %>
              </div>
              
              <div style="float: right;">
                <% if post.user == current_user %>
                  <%= link_to 'Edit', edit_post_path(post), class:"btn btn-warning" %>
                  <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

                <% end %>
              </div> 
            </div>
          </div>
        </div>
    <% end %>
  </div>  

</div> 