config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  post 'messages', to: 'messages#create'
 
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  
  root to: "posts#index"

  get "/home", to: "home#index"
  
  resources :posts
  get "/show_notification", to: "posts#show_notification"
  
  resources :comments

  resources :likes, only: [:create, :destroy]
  
  resources :user_profile

  get '/another_user/:id', to: "user_profile#another_user"

  resources :friendshipes

  get '/add_new_friend', to: "friendshipes#add_new_friend"

  get '/friend', to: "friendshipes#friend"
 
  get '/see_friend_request', to: "friendshipes#see_friend_request"

  get '/chat', to: "pages#chat"


  resources :rooms do
    resources :msgs
  end

  get 'user/:id', to: 'users#show', as: 'user'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :body, presence: true  
end

app/models/friendship.rb
class Friendship < ApplicationRecord	
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit {
    MessageBroadcastJob.perform_later(self)
  }
end

app/models/msg.rb
class Msg < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private

      is_participant = Participant.where(user_id: user.id, room_id: room.id).first
      throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_one_attached :image 
	validates :title, presence: true, length: { maximum: 20 }
  validates :description, presence: true 
  validates :image, presence: true
  scope :recent_first, -> {order(created_at: :desc)}
  
end

app/models/room.rb
class Room < ApplicationRecord
	validates_uniqueness_of :name
	scope :public_rooms, -> {where(is_private: false)}
	after_create_commit { broadcast_if_public }
	has_many :msgs
	has_many :participants, dependent: :destroy
	
 def broadcast_if_public
   broadcast_append_to "rooms" unless self.is_private
 end
 def self.create_private_room(users, room_name)
   single_room = Room.create(name: room_name, is_private: true)
   users.each do |user|
     Participant.create(user_id: user.id, room_id: single_room.id)
   end
   single_room
 end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    scope :all_except, ->(user) {where.not(id:user)} 

    validates :email,
      presence: true,
      length: { maximum: 50 },
      format: { with: URI::MailTo::EMAIL_REGEXP },
      uniqueness: true
    
    validates :name, presence: true,  
              :length => { minimum: 4 },
              :uniqueness => { case_sensitive: false }
              
    validates :address, presence: true  
  
    validates :mobile_no,:presence => true,
              :numericality => true,
              :length => { :minimum => 10, :maximum => 12 }

    has_many :posts  
    has_many :comments
    has_many :likes
    has_one_attached :profilepic 

    after_create_commit { broadcast_append_to "users" } 
    has_many :msgs
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  def index
  end

  def new    
  end

  def show    
    @posts = Post.where(user_id:current_user.id)
  end

  def edit
    @comment = Comment.find(params[:id])  
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
  end  

  def another_user
    @user = User.find_by(id: params['id'])
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :image )    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_profile/add_new_friend.html.erb
<div class = "container">
<%= link_to 'Back', user_profile_path(current_user), class:"btn btn-primary" %><br>
<% User.all.each do |user| %>
	<% req = Friendship.find_by(sender_id: current_user.id, receiver_id: user.id)%>
  <% if !req.present? || req.confirmation == false %>
	  <strong style="color:#666600">
	  <%= user.name %><br>
	  <%= user.email %></strong>
	  <% if req.nil? %>
		  <%= button_to " send request", friendshipes_path(sender_id: current_user.id, receiver_id: user.id, confirmation: false), class:"btn btn-primary" %><br>
		<% else %>
		  <%= button_to "remove request", friendshipe_path(req), method: :delete, class:"btn btn-primary" %>  
		<% end %>
	<% end %>
<% end %>
</div> 

app/views/user_profile/another_user.html.erb
<%= @user.name%>
<h1>  another user </h1>

app/views/user_profile/edit.html.erb
<p> user profile edit </p>

app/views/user_profile/index.html.erb
<p>user profile index</p>

app/views/user_profile/new.html.erb
<h5>user profile new page</h5>

app/views/user_profile/see_friend_request.html.erb
<h1>Requests <%= link_to 'Back', user_profile_path(current_user), class:"btn btn-primary" %></h1>
<% @friends.each do |friend| %>
  <% user = User.find(friend.sender_id) %>
  <div class="mb-3 row">
    <label for="staticEmail" class="col-sm-2 col-form-label"><strong style="color:#666600"><%= user.name %>
      <%= user.email%></strong>
    </label>
    <div class="col-sm-10">
      <%= link_to "accept request", edit_friendshipe_path(friend.id),
    class:"btn btn-primary"  %>
    </div>
  </div>
<% end %>

app/views/user_profile/show.html.erb
<body>	
	<div class="container">
	  <div class="leftpane">
	  	<%= image_tag current_user.profilepic, {height: 168} if @current_user.profilepic.attached? %>
	  </div>
	  <div class="leftpane">
		  <strong><%= current_user.name.capitalize() %></strong><br> 
			<%= current_user.email %><br>
			<%= current_user.mobile_no %><br>
			<%= current_user.address %><br>
		   <%= link_to 'Edit', edit_user_registration_path, class:"btn btn-warning" %><br>
	  </div>
	  <div class="leftpane">
		  <%= link_to 'index post', posts_path, class:"btn btn-primary" %><br>
	    <%= link_to '+ post', new_post_path, class:"btn btn-primary" %>
	    <%= link_to 'New Friend', add_new_friend_path, class:"btn btn-primary" %><br> 
	    <%= link_to 'Friend request', see_friend_request_path, class:"btn btn-primary" %>
	    <%= link_to 'My Friend', friend_path, class:"btn btn-primary" %><br>
	  </div>
	  <div class="mypost"><h1 style="color:Tomato;"><center>My Post </center></h1> </div>

	  <div class="bottompane">
			<div class="row">
				<%@posts.each do |post| %>

					<div class="card col-md-3" style="height: 400px; background-color: #b3d9ff;">
					<h1>  </h1>
					<% if post.image.attached? %>	
				     <%= image_tag post&.image, class:"card-img-top", style: "height: 200px"%>
				    <% end %> 
					<div class="card-body">
					    <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
						    <p class="card-text"> <%= post.description %> </p>
					<div style="margin-bottom: 10px;">
						    	<%= form_with model: Comment.new do |form| %>
						        <%= hidden_field_tag :post_id, post.id %>
						        <%= form.text_field :body, placeholder: "Comment", style: "width: 150px; display: inline" %>
						        <%= form.submit 'submit' %>
			            <% end %>
						    </div>

					<div style="float: left;">
					    	    <%= post.likes.count %> 
			          		<% like = current_user.likes.find_by(post: post) %> 
								    <% if like.nil? %>
								        <%=  link_to likes_path({ like: { post_id: post.id } }), method: :post do %>
			                    <%= image_tag "like-inactive.png", style: "height: 40px;" %>
								        <% end %>
								    <% else %>
								        <%=  link_to  like_path(like), method: :delete do %>
								        <%= image_tag "like-active.png", style: "height: 40px;" %>
								        <% end %>
								    <% end %>
			          	</div>
		          
		      <div style="float: right;">
							  <%= link_to 'Edit', edit_post_path(post), class:"btn btn-warning" %>
					      <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
					</div>

				  </div>
			    </div>
        <% end %>
		</div>
  </div> 
</body>